services:
    _defaults:
        autowire: true
        bind:
            $tables: '%tables%'

    kaileysnay.pcr.listener:
        class: kaileysnay\pcr\event\main_listener
        tags:
            - { name: event.listener }
